spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/human_resources-database
    username: human_resources-database
    password: human_resources-database
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
